version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development

  seo-service:
    build:
      context: ./seo-service
    ports:
      - "8001:8001"
    environment:
      - FLASK_ENV=development
    depends_on:
      - auth-service
